# Graphiques exploratoires

## Imports et récupération des données

In [5]:
# Default
import pandas as pd
import seaborn as sns
import numpy as np
import warnings
import plotly.express as px
import time

# désactiver temporairement les avertissements
warnings.filterwarnings('ignore')

In [6]:
file_path = "https://raw.githubusercontent.com/remijul/dataset/master/Airline%20Passenger%20Satisfaction.csv"
df = pd.read_csv(file_path, sep=";", index_col=False)
df = df.drop('id', axis=1)

df.columns = ['Satisfaction', 'Gender', 'Customer_Type', 'Age', 'Type_of_Travel',
                    'Class', 'Flight_Distance', 'Seat_comfort', 'Departure_Arrival_time_convenient', 
                    'Food_and_drink', 'Gate_location', 'Inflight_wifi_service', 'Inflight_entertainment', 'Online_support', 
                    'Ease_of_Online_booking', 'On_board_service', 'Leg_room_service', 'Baggage_handling',
                    'Checkin_service', 'Cleanliness', 'Online_boarding', 'Departure_Delay_in_Minutes', 'Arrival_Delay_in_Minutes']

df

,Satisfaction,Gender,Customer_Type,Age,Type_of_Travel,Class,Flight_Distance,Seat_comfort,Departure_Arrival_time_convenient,Food_and_drink,...,Online_support,Ease_of_Online_booking,On_board_service,Leg_room_service,Baggage_handling,Checkin_service,Cleanliness,Online_boarding,Departure_Delay_in_Minutes,Arrival_Delay_in_Minutes
0,satisfied,Female,Loyal Customer,65,Personal Travel,Eco,265,0,0,0,...,2,3,3,0,3,5,3,2,0,0.0
1,satisfied,Male,Loyal Customer,47,Personal Travel,Business,2464,0,0,0,...,2,3,4,4,4,2,3,2,310,305.0
2,satisfied,Female,Loyal Customer,15,Personal Travel,Eco,2138,0,0,0,...,2,2,3,3,4,4,4,2,0,0.0
3,satisfied,Female,Loyal Customer,60,Personal Travel,Eco,623,0,0,0,...,3,1,1,0,1,4,1,3,0,0.0
4,satisfied,Female,Loyal Customer,70,Personal Travel,Eco,354,0,0,0,...,4,2,2,0,2,4,2,5,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129875,satisfied,Female,disloyal Customer,29,Personal Travel,Eco,1731,5,5,5,...,2,2,3,3,4,4,4,2,0,0.0
129876,neutral or dissatisfied,Male,disloyal Customer,63,Personal Travel,Business,2087,2,3,2,...,1,3,2,3,3,1,2,1,174,172.0
129877,neutral or dissatisfied,Male,disloyal Customer,69,Personal Travel,Eco,2320,3,0,3,...,2,4,4,3,4,2,3,2,155,163.0
129878,neutral or dissatisfied,Male,disloyal Customer,66,Personal Travel,Eco,2450,3,2,3,...,2,3,3,2,3,2,1,2,193,205.0
129879,neutral or dissatisfied,Female,disloyal Customer,38,Personal Travel,Eco,4307,3,4,3,...,3,4,5,5,5,3,3,3,185,186.0

## Graphs

In [7]:
df_graph = df.copy()

colonnes_num = list(df_graph.select_dtypes(include=['int', 'float']).columns)
colonnes_cat = list(df_graph.select_dtypes(include=['object']).columns)

print(f'Colonnes numériques : {colonnes_num}')
print(f'Colonnes catégorielles : {colonnes_cat}')

df_graph['Satisfaction'] = df_graph['Satisfaction'].replace({'satisfied': 1, 'neutral or dissatisfied': 0})
# df_graph['Gender'] = df_graph['Gender'].replace({'Female': 1, 'Male': 0})
# df_graph['Customer_Type'] = df_graph['Customer_Type'].replace({'Loyal Customer': 1, 'disloyal Customer': 0})
# df_graph['Type_of_Travel'] = df_graph['Type_of_Travel'].replace({'Personal Travel': 1, 'Business travel': 0})
# df_graph['Class'] = df_graph['Class'].replace({'Business': 2, 'Eco Plus': 1, 'Eco': 0})

Colonnes numériques : ['Age', 'Flight_Distance', 'Seat_comfort', 'Departure_Arrival_time_convenient', 'Food_and_drink', 'Gate_location', 'Inflight_wifi_service', 'Inflight_entertainment', 'Online_support', 'Ease_of_Online_booking', 'On_board_service', 'Leg_room_service', 'Baggage_handling', 'Checkin_service', 'Cleanliness', 'Online_boarding', 'Departure_Delay_in_Minutes', 'Arrival_Delay_in_Minutes']
Colonnes catégorielles : ['Satisfaction', 'Gender', 'Customer_Type', 'Type_of_Travel', 'Class']

In [8]:
df_graph_bar = df_graph.loc[:, ['Satisfaction', 'Inflight_entertainment', 'Class']]
print (df_graph_bar)
#fig = px.bar(df_graph_bar, x="Satisfaction", y="Inflight_entertainment", color="Class", title="Long-Form Input")
#fig.show()

        Satisfaction  Inflight_entertainment     Class
0                  1                       4       Eco
1                  1                       2  Business
2                  1                       0       Eco
3                  1                       4       Eco
4                  1                       3       Eco
...              ...                     ...       ...
129875             1                       5       Eco
129876             0                       1  Business
129877             0                       2       Eco
129878             0                       2       Eco
129879             0                       3       Eco

[129880 rows x 3 columns]